//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrinterMonitorLibrary.ModelLibrary.EntityFrameworkLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECK_WEBTOKEN
    {
        public int id { get; set; }
        public string Token { get; set; }
        public string EncyptedToken { get; set; }
        public System.DateTime DateOfrequest { get; set; }
        public int Status { get; set; }
        public string HashedToken { get; set; }
        public string Username { get; set; }
        public string SmartCardID { get; set; }
        public string HashedSmartCardID { get; set; }
    }
}
