//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrinterMonitorLibrary.ModelLibrary.EntityFrameworkLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrinterFeed
    {
        public long ID { get; set; }
        public string PrinterUID { get; set; }
        public int RibbonCount { get; set; }
        public int CardPrinted { get; set; }
        public bool Status { get; set; }
        public bool LatestFeed { get; set; }
        public System.DateTime DateofReport { get; set; }
    }
}
