//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrinterMonitorLibrary.ModelLibrary.EntityFrameworkLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrinterFeed
    {
        public long ID { get; set; }
        public string PrinterUID { get; set; }
        public string PrinterSerialNumber { get; set; }
        public Nullable<int> RibbonCount { get; set; }
        public Nullable<int> CardPrinted { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> LatestFeed { get; set; }
        public Nullable<System.DateTime> DateofReport { get; set; }
        public string PrinterType { get; set; }
    }
}
