//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrinterMonitorLibrary.ModelLibrary.EntityFrameworkLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Printer
    {
        public long ID { get; set; }
        public string PrinterUID { get; set; }
        public string PrinterSrNo { get; set; }
        public string PrinterName { get; set; }
        public string PrinterBrand { get; set; }
        public Nullable<long> BranchID { get; set; }
        public Nullable<System.DateTime> DateofEnrollment { get; set; }
    
        public virtual Branch Branch { get; set; }
    }
}
