//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrinterMonitorLibrary.ModelLibrary.EntityFrameworkLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmartCard
    {
        public SmartCard()
        {
            this.Users = new HashSet<User>();
        }
    
        public long ID { get; set; }
        public string EncryptedSmartCardID { get; set; }
        public string HashedSmartCardID { get; set; }
        public bool Allocated { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
