//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrinterMonitorLibrary.ModelLibrary.EntityFrameworkLib
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        public long ID { get; set; }
        [Required]
        public string Lastname { get; set; }
        [Required]
        public string Othernames { get; set; }
        [Required]
        public string Gender { get; set; }
        [Required]
        [DisplayName("Phone Number")]
        public string PhoneNumber { get; set; }
        [Required]
        [EmailAddress(ErrorMessage="Invalid Email Address")]
        public string Email { get; set; }
        [Required]
        public string Username { get; set; }
        [Required]
        [DisplayName("User Role")]
        public Nullable<long> UserRole { get; set; }
        public string HashedPassword { get; set; }
        public Nullable<long> SmartCardID { get; set; }
        [Required]
        [DisplayName("User Branch")]
        public Nullable<long> UserBranch { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> FirstTime { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Role Role { get; set; }
        public virtual SmartCard SmartCard { get; set; }
    }
}
